name: build
on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: write

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 19

      - run: ./gradlew build check
